name: Get list of changed files
run-name: List Changed files
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # this is required to get the full history

      - name: List branches
        run: git branch -r

      - name: Get all changed files
        id: changed_files
        run: |
            git fetch origin main:${{ github.ref_name }}-main
            git fetch origin ${{ github.ref_name }}:${{ github.ref_name }}-current
            git diff --name-only ${{ github.ref_name }}-main...${{ github.ref_name }}-current
      - name: Print the changed files
        run: |
            changed_files=$(git diff --name-only ${{ github.ref_name }}-main...${{ github.ref_name }}-current -- 'pub/i18n/locales/en/**.json')
            echo "Changed files:"
            echo "$changed_files"

      - name: Get list of changed JSON files
        id: files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only ${{ github.ref_name }}-main...${{ github.ref_name }}-current -- 'pub/i18n/locales/en/**.json')" >> $GITHUB_ENV

      - name: Use Changed Files
        run: |
          echo "Changed Files:"
          echo $CHANGED_FILES

    