name: Pull from Lokalise
run-name: Pull from Lokalise [${{ github.ref_name }}] ${{ github.event.after }}
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PREVIOUS_COMMIT: ${{ github.event.after }}
      GITHUB_CURRENT_COMMIT: ${{ github.event.before }}
      VAR_LOKALISE_API_TOKEN: ${{ secrets.API_TOKEN }}
      VAR_LOKALISE_PROJECT_ID: ${{ vars.PROJECT_ID }}
      VAR_LOKALISE_SOURCE_LANG_ISO: ${{ vars.SOURCE_LANG }}
      VAR_FOLDER_PATH: ${{ vars.FOLDER_PATH }}
      VAR_GITHUB_NEW_BRANCH_NAME: ${{ vars.LOCALIZATION_BRANCH_NAME }}
      GITHUB_BASE_BRANCH_NAME: ${{ github.ref_name }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3

      # Download and install the Lokalise CLI tool
      - name: Install Lokalise CLI
        run: curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh

      # Create a branch for the localization files
      - name: Create branch
        run: |
          git checkout -b ${{ env.VAR_GITHUB_NEW_BRANCH_NAME }}

      # Pull localization files from Lokalise
      - name: Pull localization files from Lokalise
        run: |
          ./bin/lokalise2 --token="${{ env.VAR_LOKALISE_API_TOKEN }}" \
                          --project-id="${{ env.VAR_LOKALISE_PROJECT_ID }}" \
                          file download \
                          --format json \
                          --original-filenames=true \
                          --directory-prefix="/" \
                          --export-sort a_z \
                          --filter-data translated \
                          --include-tags=${{ github.ref_name }}

      - name: Commit
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add ./${{ vars.FOLDER_PATH }}/**/*.json -- ':!${{ vars.FOLDER_PATH }}/${{ env.VAR_LOKALISE_SOURCE_LANG_ISO }}/*.json'
          if [[ -z $(git status --untracked-files=no --porcelain) ]]; then
            echo "No changes"
          else
            git commit -m 'Translations update'
            git push origin ${{ env.GITHUB_NEW_BRANCH_NAME }}

      - name: Create Pull Request
        run: |
          gh pr create --base ${{ env.GITHUB_BASE_BRANCH_NAME }} --head ${{ env.VAR_GITHUB_NEW_BRANCH_NAME }} --title "Lokalise translations update" --body ""
