name: Pull from Lokalise
run-name: Pull from Lokalise [${{ github.ref_name }}] ${{ github.event.after }}
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PREVIOUS_COMMIT: ${{ github.event.after }}
      GITHUB_CURRENT_COMMIT: ${{ github.event.before }}
      VAR_LOKALISE_API_TOKEN: ${{ secrets.API_TOKEN }}
      VAR_LOKALISE_PROJECT_ID: ${{ vars.PROJECT_ID }}
      VAR_LOKALISE_SOURCE_LANG_ISO: ${{ vars.SOURCE_LANG }}
      VAR_FOLDER_PATH: ${{ vars.FOLDER_PATH }}
      VAR_TRANSLATION_BRANCH_NAME: ${{ vars.TRANSLATION_BRANCH_NAME }}
      GITHUB_BASE_BRANCH_NAME: ${{ github.ref_name }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3

      # Download and install the Lokalise CLI tool
      - name: Install Lokalise CLI
        run: curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh

      # Create a branch for the localization files
      - name: Create branch
        run: |
          git checkout -b "${{ github.ref_name }}-${{ github.sha }}-${{ env.VAR_TRANSLATION_BRANCH_NAME }}"

      # Pull localization files from Lokalise
      - name: Pull localization files from Lokalise
        run: |
          ./bin/lokalise2 --token="${{ env.VAR_LOKALISE_API_TOKEN }}" \
                          --project-id="${{ env.VAR_LOKALISE_PROJECT_ID }}" \
                          file download \
                          --format json \
                          --original-filenames=true \
                          --directory-prefix="/" \
                          --export-sort a_z \
                          --filter-data translated \
                          --include-tags=${{ github.ref_name }}

      # Commit changes with debugging
      - name: Commit
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in current directory:"
          ls -al

          echo "Git status before adding files:"
          git status

          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          echo "Adding files to staging area:"
          git add ./${{ vars.FOLDER_PATH }}/**/*.json -- ':!${{ vars.FOLDER_PATH }}/${{ env.VAR_LOKALISE_SOURCE_LANG_ISO }}/*.json'

          echo "Git status after adding files:"
          git status

          if [[ -z $(git status --untracked-files=no --porcelain) ]]; then
            echo "No changes to commit"
          else
            echo "Committing changes"
            git commit -m 'Translations update'
            
            echo "Git log after commit:"
            git log -1

            echo "Pushing changes to remote repository"
            git push origin "${{ github.ref_name }}-${{ env.VAR_TRANSLATION_BRANCH_NAME }}"
          fi

      - name: Create Pull Request
        run: |
            echo "Current directory: $(pwd)"
            echo "Files in current directory:"
            ls -al

            echo "Git status before creating PR:"
            git status

            # Print details of uncommitted changes
            echo "Uncommitted changes:"
            git diff --name-only  # Show modified files not yet staged
            git diff --cached --name-only  # Show staged files

            # Ensure git configuration is correct
            git config --global user.name "${GITHUB_ACTOR}"
            git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

            # Create the pull request
            echo "Creating Pull Request..."
            gh pr create --base ${{ env.GITHUB_BASE_BRANCH_NAME }} \
                        --head "${{ github.ref_name }}-${{ env.VAR_TRANSLATION_BRANCH_NAME }}" \
                        --title "Lokalise translations update" \
                        --body ""

            echo "Pull Request created successfully."