name: Push to Lokalise
run-name: Push to Lokalise [${{ github.ref_name }}] ${{ github.event.after }}
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "${{ var.FOLDER_PATH }}/**.json"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        GITHUB_PREVIOUS_COMMIT: ${{ github.event.after }}
        GITHUB_CURRENT_COMMIT: ${{ github.event.before }}
        VAR_LOKALISE_API_TOKEN: ${{ secrets.API_TOKEN }}
        VAR_LOKALISE_PROJECT_ID: ${{ vars.PROJECT_ID }}
        VAR_LOKALISE_SOURCE_LANG_ISO: ${{ vars.SOURCE_LANG }}
        VAR_FOLDER_PATH: ${{ vars.FOLDER_PATH }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Lokalise CLI
        run: curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh
      - name: List all localization files in path "${{ vars.FOLDER_PATH }}"
        run: git ls-files "${{ vars.FOLDER_PATH }}/**.json"
      - name: Push localization files to Lokalise
        run: |
             while read file 
             do 
                if [ -f $file ]
                then
                  ./bin/lokalise2 --token ${{ env.VAR_LOKALISE_API_TOKEN }} --project-id ${{ env.VAR_LOKALISE_PROJECT_ID }} file upload --file="${file}" --lang-iso ${{ env.VAR_LOKALISE_SOURCE_LANG_ISO }} --replace-modified --include-path --use-automations=true --cleanup-mode --poll-timeout 120s
                fi
             done < <(git ls-files "${{ env.VAR_FOLDER_PATH }}/**.json")