name: Push to Lokalise
run-name: Push to Lokalise [${{ github.ref_name }}] ${{ github.event.after }}
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        GITHUB_PREVIOUS_COMMIT: ${{ github.event.after }}
        GITHUB_CURRENT_COMMIT: ${{ github.event.before }}
        VAR_LOKALISE_API_TOKEN: ${{ secrets.API_TOKEN }}
        VAR_LOKALISE_PROJECT_ID: ${{ vars.PROJECT_ID }}
        VAR_LOKALISE_SOURCE_LANG_ISO: ${{ vars.SOURCE_LANG }}
        VAR_FOLDER_PATH: ${{ vars.FOLDER_PATH }}
    steps:
      - uses: actions/checkout@v3
      
      # Download and install the Lokalise CLI tool
      - name: Install Lokalise CLI
        run: curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh

      # Identify and process each changed JSON file within the specified folder path and upload to Lokalise  
      - name: Push localization files to Lokalise
        run: |
            changed_files=$(git diff --name-only $GITHUB_PREVIOUS_COMMIT $GITHUB_CURRENT_COMMIT -- ${{ env.VAR_FOLDER_PATH }}/${{ env.VAR_LOKALISE_SOURCE_LANG_ISO }}/ )
            for file in $changed_files
            do 
              if [[ $file == *.json ]]
              then
                ./bin/lokalise2 --token="${{ env.VAR_LOKALISE_API_TOKEN }}" \
                  --project-id="${{ env.VAR_LOKALISE_PROJECT_ID }}" \
                  file upload \
                  --file="$file" \
                  --lang-iso="${{ env.VAR_LOKALISE_SOURCE_LANG_ISO }}" \
                  --replace-modified \
                  --include-path \
                  --use-automations=true \
                  --distinguish-by-file \
                  --poll \
                  --poll-timeout=120s \
                  --tag-inserted-keys \
                  --tag-skipped-keys=true \
                  --tag-updated-keys \
                  --tags ${{ github.ref_name }} 
              fi
            done